project:
  type: website
  resources: 
    - data/therapie.csv
  output-dir: docs
  render:
  - index.qmd
  - pages/*.qmd
  
  
website:
  title: Anova Demo
  site-url: https://psylu.github.io/anova_demo
  reader-mode: true
  
  sidebar:
    style: floating
    search: true
    contents:
    - pages/anova_demo_between.qmd
    - pages/anova_demo_mixed.qmd
format:
  html:
    theme:
      light:
      - flatly
      - styles/light.scss
      dark:
      - darkly
      - styles/dark.scss
editor:
  render-on-save: true
